In [1]:
import pandas as pd
import arff

In [4]:
df = pd.read_csv('datos2.csv', sep=';', dtype='str')
df

,order_id,100% Whole Wheat Bread,Apple Honeycrisp Organic,Asparagus,Bag of Organic Bananas,Banana,Blueberries,Boneless Skinless Chicken Breasts,Bunched Cilantro,Carrots,...,Raspberries,Red Peppers,Red Vine Tomato,Seedless Red Grapes,Small Hass Avocado,Sparkling Water Grapefruit,Spring Water,Strawberries,Unsweetened Almondmilk,Yellow Onions
0,2,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,5,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,10,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19830,31309,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19831,31310,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
19832,31312,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19833,31315,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19834,31319,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
# df to arff
data = {
    'description': u'',
    'relation': 'relation',
    'attributes': [(col, df[col].unique().tolist()) for col in df.columns],
    'data': df.values
}

# Write
with open('yourfile.arff', 'w') as f:
    arff.dump(data, f)